name: Run Docker
on:
  push:
  workflow_call:
    secrets:
      INSTA_USERNAME:
        required: true
        description: "Insta username"
      INSTA_PASSWORD:
        required: true
        description: "Insta password"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v3
        with:
          image: instapy/instapy:latest
          options: -v ${{ github.workspace }}/dolboinsta.py:/code/docker_quickstart.py -v ${{ github.workspace }}:/code
          run: insta_username=${{ secrets.INSTA_USERNAME }} insta_password=${{ secrets.INSTA_PASSWORD }} python docker_quickstart.py
