name: Run Docker
on:
  push:
  workflow_call:
    secrets:
      INSTA_USERNAME:
        required: true
        description: "Insta username"
      INSTA_PASSWORD:
        required: true
        description: "Insta password"


jobs:
  query-insta:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v3
        with:
          image: instapy/instapy:latest
          options: >
            -v ${{ github.workspace }}/dolboinsta.py:/code/docker_quickstart.py
            -v ${{ github.workspace }}:/code
            -e insta_username=${{ secrets.INSTA_USERNAME }}
            -e insta_password=${{ secrets.INSTA_PASSWORD }}
          run: python docker_quickstart.py
