name: Run Docker
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v3
        with:
          image: instapy/instapy:latest
          options: -v ${{ github.workspace }}/dolboinsta.py:/code/docker_quickstart.py -v ${{ github.workspace }}:/code -e insta_password=${{ secrets.INSTA_PASSWORD }} -e insta_username=${{ secrets.INSTA_USERNAME }}
          run: python docker_quickstart.py
